import "./globals.css";
import Navbar from "./components/Navbar";
import Header from "./components/Header";

export const metadata = {
  title: "Movie API",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Navbar />
        <Header />
        {children}
      </body>
    </html>
  );
}
